### ISSUE TITLE
Problema col download

### ISSUE THREAD

**Issue by ArcadeZone** [Leone25/sanoma-downloader#5]
Buongiorno, ho seguito le tue istruzioni ma quando provo a scaricare un libro, mi rimanda questo errore. Come posso risolverlo?
![Foto 1](https://github.com/user-attachments/assets/c2bbe602-7f81-43b2-ac0d-9a95d3b6852e)

**Comment by Leone25** [comment]
di solito, quell'errore indica che inkscape non é accessibile in path, cioè il terminale.

puoi verificare provando ad aprire il terminale esattamente come hai fatto per eseguire lo script e scrivere `inkscape` e premere invio. Se ti si apre inkscape allora il problema é un altro, se invece ti dice "comando non trovato" o qualcosa di simile, allora devi aggiungere inkscape a path.

**Comment by ArcadeZone** [comment]
Funziona, tutto perfetto. Grazie del supporto.
