### ISSUE TITLE
Error: ENOENT: no such file or directory, scandir 'C:\...\sanoma-downloader-main\tmp\pages'

### ISSUE THREAD

**Issue by paololami88** [Leone25/sanoma-downloader#6]
The script doesn't seem to be working anymore. I can log-in correctly and look at the list of books, but when I choose the book's gedi it gets stuck at Downloading 

Here's the full error:
"Enter the book's gedi: 1112121
Fetching book data
Downloading Con-filosofare 1A
Extracting zip
node:internal/fs/promises:950
  const result = await PromisePrototypeThen(
                 ^

Error: ENOENT: no such file or directory, scandir 'C:\Users\myname\Desktop\sanoma-downloader-main\tmp\pages'
    at async Object.readdir (node:internal/fs/promises:950:18)
    at async ZipFile.<anonymous> (file:///C:/Users/myname/Desktop/sanoma-downloader-main/index.js:157:18) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'scandir',
  path: 'C:\\Users\\myname\\Desktop\\sanoma-downloader-main\\tmp\\pages'
}

Node.js v22.11.0"

**Comment by paololami88** [comment]
@jacopeste05 are you having the same issue?

**Comment by jacopeste05** [comment]
yes 😢

**Comment by Leone25** [comment]
Hello, I have fixed the issue and uploaded an update, please download the new version and try again.

**Comment by paololami88** [comment]
Thank you! It's working properly now!
