### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by gab-viar** [Leone25/sanoma-downloader#7]
it seems to be downloading correclty but then it pops this out
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ENOENT: no such file or directory, scandir 'tmp/pages'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: 'tmp/pages'
}

**Comment by paololami88** [comment]
I've reported the same issue here:
https://github.com/Leone25/sanoma-downloader/issues/6
I hope the developer is reading this soon and is going to help us!

**Comment by Leone25** [comment]
Hello, I have fixed the issue and uploaded an update, please download the new version and try again.
